1. Import Dependencies

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

2. Load the Dataset

In [2]:
df=pd.read_csv("day.csv")
df.drop(df.columns[0],inplace=True,axis=1)
df.head()

Date  Temperature
0  2023-01-01          9.2
1  2023-01-02          7.4
2  2023-01-03          7.6
3  2023-01-04          7.8
4  2023-01-05          9.0

In [3]:
df['Date'] = pd.to_datetime(df[df.columns[0]])
df['day'] = df['Date'].dt.day
df['month'] = df['Date'].dt.month
df['year'] = df['Date'].dt.year
df1=df.drop(columns=["Temperature","Date"])
df=pd.concat([df1,df['Temperature']],axis=1)
df.head()

day  month  year  Temperature
0    1      1  2023          9.2
1    2      1  2023          7.4
2    3      1  2023          7.6
3    4      1  2023          7.8
4    5      1  2023          9.0

3. Split the Dataset

In [4]:
X=df[df.columns[:-1]].values
y=df[df.columns[-1]].values

In [5]:
X_train ,X_temp ,y_train ,y_temp =train_test_split(X,y , test_size=0.2 ,random_state=0)
X_valid ,X_test ,y_valid ,y_test =train_test_split(X_temp ,y_temp , test_size=0.4 ,random_state=0)

In [8]:
X_train.shape,y_train.shape

((292, 3), (292,))

4. Using RandomForest Algorithm to Train Data

In [13]:
reg=RandomForestRegressor()
reg.fit(X_train,y_train)

RandomForestRegressor()

In [14]:
reg.score(X_test,y_test)

0.9752016346058993

In [15]:
y_pred_lr=reg.predict(X_test)
y_pred_lr,y_test

(array([22.80412702, 39.339     , 21.87812702, 23.34717425, 31.51      ,
        23.39812702, 25.69612702, 42.711     , 19.156     , 18.33987298,
        34.2       , 19.236     , 37.971     , 14.65587298, 14.98      ,
        12.594     , 14.21587298, 41.65      , 19.984     , 28.832     ,
        27.482     , 27.656     , 20.694     , 26.46212702, 27.482     ,
        28.436     , 16.962     , 32.782     , 18.99187298, 37.73212702]),
 array([22.73012702, 39.3       , 23.53012702, 25.06987298, 30.8       ,
        25.33012702, 23.53012702, 42.1       , 20.3       , 18.06987298,
        32.3       , 21.5       , 37.8       , 15.06987298, 14.9       ,
        14.7       , 14.86987298, 40.5       , 20.9       , 29.7       ,
        29.2       , 27.7       , 20.7       , 26.33012702, 28.6       ,
        28.2       , 17.5       , 31.        , 19.26987298, 35.73012702]))

In [16]:
X_train[0]

array([  23,   10, 2023], dtype=int32)

5. Predict New Date Temprature

In [27]:
new_date=np.array([[21,8,2024]])

In [28]:
prediction=reg.predict(new_date)
prediction

array([30.534])